# Dependencies
markdown:         redcarpet
highlighter:      pygments

exclude:          ['.asset_pipeline', 'deploy.sh', 'server-script.sh']

# Permalinks
#permalink:        pretty
permalink:        /blog/:title

# Setup
title:            Joe Kampschmidt's Code
description:      "a pragmatic approach to web and software development"
url:              https://www.jokecamp.com
#url:              http://localhost:4000
baseurl:          /

author:
  name:           'Joe Kampschmidt'
  url:            https://twitter.com/jokecamp
  email:          joe.kampschmidt@gmail.com

githubProject:    https://github.com/jokecamp/jokecamp.com/
githubBranch:     tree/master/

# Custom vars
github:           https://github.com/jokecamp
twitter:          https://twitter.com/jokecamp
stackoverflow:    http://stackoverflow.com/users/215502/kampsj

version:          1.0

asset_pipeline:
  bundle: true            # Default = true
  compress: true          # Default = true
  output_path: assets     # Default = assets
  display_path: assets       # Default = nil
  gzip: true              # Default = false
